//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FraudTransactions.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int step { get; set; }
        public string type { get; set; }
        public int amount { get; set; }
        public string nameOrig { get; set; }
        public int oldBalanceOrig { get; set; }
        public int newBalanceOrig { get; set; }
        public string nameDest { get; set; }
        public int oldBalanceDest { get; set; }
        public int newBalanceDest { get; set; }
        public bool isFraud { get; set; }
        public bool isFlaggedFraud { get; set; }
    }
}
